// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkomkxdjslezoqmygamg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrb21reGRqc2xlem9xbXlnYW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDc0NDksImV4cCI6MjA3NDYyMzQ0OX0.S6tHQKWwxUWu5MxKYUKjsQMKOji7RGCvXaqhMvx0IUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});